name: Publish docs
on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'mkdocs.yml'
permissions:
  contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install mkdocs-material mkdocstrings[python] mkdocs-click
        - name: Deploy
          run: mkdocs gh-deploy --force
